# HC stands for haskell compiler, FLAGS stands for flags
HC = ghc
FLAGS = 

all: purpleAmerica

# Compiles Main.hs with flags
purpleAmerica:
	$(HC) Main.hs $(FLAGS)

# Removes all objects and binaries
clean:
	rm *.o *.hi Main